[SWAG-019] .github ,workflows and playwright test yaml updated

diff --git a/.github/workflows/playwright-tests.yml b/.github/workflows/playwright-tests.yml
--- a/.github/workflows/playwright-tests.yml
+++ b/.github/workflows/playwright-tests.yml
@@ -1,4 +1,4 @@
-name: AIT Playwright Tests
+name: SwagLabs Playwright Tests
 
 on:
   push:
@@ -22,22 +22,16 @@ jobs:
         with:
           node-version: '20'
 
-      - name: Clear npm cache
-        run: npm cache clean --force
-
       - name: Install dependencies
-        run: npm install --unsafe-perm=true --allow-root
+        run: npm install
 
-      # Install Playwright directly through npm instead of npx
       - name: Install Playwright Browsers
-        run: |
-          npm install playwright
-          npx playwright install
+        run: npx playwright install
 
       - name: Run Playwright tests
         run: |
-          CI=true npx playwright test --reporter=html,allure-playwright || echo "Tests failed, review logs."
-          
+          CI=true npx playwright test --reporter=html || echo "Tests failed, review logs."
+
           # Always check if the report directory exists
           if [ -d playwright-report ]; then
             echo "artifact_exists=true" >> $GITHUB_ENV
@@ -49,37 +43,12 @@ jobs:
         if: env.artifact_exists == 'true'
         uses: actions/upload-artifact@v4
         with:
-          name: AIT-Playwright-Test-Artifacts
+          name: SwagLabs-Playwright-Test-Artifacts
           path: test-results/
-
+          
       - name: Upload HTML Report
         if: env.artifact_exists == 'true'
         uses: actions/upload-artifact@v4
         with:
-          name: AIT-Playwright-HTML-Report
+          name: SwagLabs-Playwright-HTML-Report
           path: playwright-report/
-
-      - name: Upload Allure Results
-        if: env.artifact_exists == 'true'
-        uses: actions/upload-artifact@v4
-        with:
-          name: AIT-Playwright-Allure-Results
-          path: test-results/allure-results/
-
-      - name: Run Accessibility Tests
-        run: |
-          CI=true npx playwright test --reporter=html,allure-playwright --project=Chromium --grep "Accessibility Testing Suite" || echo "Accessibility tests failed, review logs."
-
-          # Always check if the report directory exists for accessibility tests
-          if [ -d accessibility-reports ]; then
-            echo "artifact_exists=true" >> $GITHUB_ENV
-          else
-            echo "artifact_exists=false" >> $GITHUB_ENV
-          fi
-
-      - name: Upload Accessibility Reports
-        if: env.artifact_exists == 'true'
-        uses: actions/upload-artifact@v4
-        with:
-          name: AIT-Playwright-Accessibility-Reports
-          path: reports/
